[versions]
kotlin = "1.9.21"
coroutines = "1.7.0"
retrofit = "2.9.0"
moshi = "1.14.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit"}
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit"}

moshi= { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin= { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version = "4.10.0"}

[plugins]
